name: Terraform checks

on:
  push:
    branches:
      - main
    paths:
      - "infrastructure/**"
      - ".github/workflows/terraform.yaml"
  pull_request:
    paths:
      - "infrastructure/**"
      - ".github/workflows/terraform.yaml"

jobs:
  terraform-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkov security scan
        id: checkov
        uses: bridgecrewio/checkov-action@v12.641.0
        with:
          directory: infrastructure
          framework: terraform
          output_format: cli
          download_external_modules: true
        continue-on-error: true
      
      - name: Terraform plan
        run: make check
        working-directory: infrastructure
          
